Feature/projects list
BinaryStudioAcademy/bsa-2020-TaskyHusky pull request #217
Opened 2020-08-24 15:43 UTC by Vitaliy-ko

2020-08-24 21:16 UTC, taras-dubyk requested changes

2020-08-24 21:16 UTC, taras-dubyk commented on client/src/components/common/UserAvatar/index.tsx
> +				<Image src={user.avatar} className={[small && styles.small, styles.avatarImage].join(' ')} circular />
Use [classnames](https://www.npmjs.com/package/classnames) package for such cases.
```suggestion
				<Image src={user.avatar} className={classnames(styles.avatarImage, { [styles.small]: small })} circular />
```

2020-08-26 18:12 UTC, Vitaliy-ko commented on client/src/components/common/UserAvatar/index.tsx
> +				<Image src={user.avatar} className={[small && styles.small, styles.avatarImage].join(' ')} circular />
Сompleted

2020-08-28 16:51 UTC, YrPryhoda commented on client/src/containers/Projects/table.tsx
> +							className={[styles.table__header_cell, styles.column__lead].join(' ')}
If you started using classnames npm package, use it or backticket template

2020-08-28 17:02 UTC, merged