Added en, ru, ua localization to Team page and its components
BinaryStudioAcademy/bsa-2020-TaskyHusky pull request #239
Opened 2020-08-27 15:34 UTC by YrPryhoda

2020-08-27 20:04 UTC, R-Mielamud requested changes

2020-08-27 20:04 UTC, R-Mielamud commented on client/src/components/TeamWorkedProjects/index.tsx
>  						</>
there_are_no_projects_which_have_been_started_yet

2020-08-27 20:04 UTC, R-Mielamud commented on client/src/translations/ua.ts
>  };
Remove space before }

2020-08-27 20:04 UTC, R-Mielamud commented on client/src/translations/ru.ts
>  };
Remove space before }

2020-08-27 20:04 UTC, R-Mielamud commented on client/src/translations/en.ts
>  };
Remove space before }

2020-08-28 07:37 UTC, YrPryhoda commented on client/src/components/TeamDevsCard/index.tsx
>  					defaultValue={teamDescription}
it's not difficult. ok

2020-08-28 07:37 UTC, YrPryhoda commented on client/src/components/TeamLinks/createLink.tsx
>  						/>
renamed

2020-08-28 07:37 UTC, YrPryhoda commented on client/src/components/TeamWorkedProjects/index.tsx
>  						</>
corrected

2020-08-28 07:59 UTC, R-Mielamud approved these changes
All fine

2020-08-28 08:03 UTC, merged