Feature/project labels
BinaryStudioAcademy/bsa-2020-TaskyHusky pull request #281
Opened 2020-08-31 22:50 UTC by Vitaliy-ko

2020-09-03 13:25 UTC, timagixe requested changes

2020-09-03 13:25 UTC, timagixe commented on client/src/components/common/ConfirmModal/styles.module.scss
> +}
We can remove this file.

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/ProjectLabels/index.tsx
> +					<Button className={styles.primary__button} onClick={onOpenAddLabelModal}>
```suggestion
					<Button className="primaryBtn" onClick={onOpenAddLabelModal}>
```

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/ProjectLabels/index.tsx
> +										className={styles.primary__button_basic}
```suggestion
										className='contentBtn'
```

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/ProjectLabels/index.tsx
> +										color="red"
```suggestion
										className="cancelBtn"
```

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/ProjectLabels/styles.module.scss
> +}
Let's remove it and use className="primaryBtn" instead.

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/ProjectLabels/styles.module.scss
> +}
New line at the end of file.

2020-09-03 13:25 UTC, timagixe commented on client/src/containers/Projects/table.tsx
> +									<span>{`${lead.firstName} ${lead.lastName}`}</span>
```suggestion
									<span>{getUsername(lead)}</span>
```

2020-09-03 13:25 UTC, timagixe commented on client/src/services/projects.service.ts
> +}): Promise<WebApi.Entities.ProjectLabel> => {
```suggestion
export const deleteLabel = async ({ projectId, labelId }: DeleteLabel): Promise<WebApi.Entities.ProjectLabel> => {
```

2020-09-03 13:25 UTC, timagixe commented on client/src/services/projects.service.ts
> +import { Label } from 'containers/ProjectLabels/logic/actionTypes';
```suggestion
import { Label, DeleteLabel } from 'containers/ProjectLabels/logic/actionTypes';
```

2020-09-03 13:25 UTC, timagixe commented on server/src/controllers/projects.controllers.ts
> +			}
Do we really need this?

From what I see `getProjectById` itself will throw an error if it cannot find project
```
		if (project === undefined) {
			next(new ErrorResponse(HttpStatusCode.NOT_FOUND, projectsErrorMessages.PROJECT_NOT_FOUND));
			return null;
		}
```

If we can remove it here then it should be removed from `updateLabel` and `deleteLabel` too.

2020-09-03 13:29 UTC, Vitaliy-ko commented on client/src/components/common/ConfirmModal/styles.module.scss
> +}
Removed

2020-09-03 13:35 UTC, Vitaliy-ko commented on client/src/containers/ProjectLabels/AddLabelModal.tsx
> +					<Button onClick={onModalClose}>{t('cancel')}</Button>
Added class cancelBtn

2020-09-03 13:36 UTC, Vitaliy-ko commented on client/src/containers/ProjectLabels/AddLabelModal.tsx
> +							<Button className={styles.primary__button} onClick={onEditLabel} loading={isLoading}>
Added primaryBtn class

2020-09-03 13:37 UTC, Vitaliy-ko commented on client/src/components/common/ConfirmModal/index.tsx
> +			<Button primary onClick={confirmAction} className={styles.primary__button}>
Added suggested changes

2020-09-03 13:38 UTC, Vitaliy-ko commented on client/src/components/common/Label/styles.module.scss
> +}
Added new line at the end of the file

2020-09-03 13:39 UTC, Vitaliy-ko commented on client/src/containers/ProjectLabels/styles.module.scss
> +}
Added new line

2020-09-03 13:42 UTC, Vitaliy-ko commented on client/src/containers/Projects/table.tsx
> +									<span>{`${lead.firstName} ${lead.lastName}`}</span>
Added suggested changes

2020-09-03 13:44 UTC, Vitaliy-ko commented on client/src/services/projects.service.ts
> +}): Promise<WebApi.Entities.ProjectLabel> => {
Added suggested changes

2020-09-03 13:45 UTC, Vitaliy-ko commented on client/src/services/projects.service.ts
> +import { Label } from 'containers/ProjectLabels/logic/actionTypes';
Added suggested changes

2020-09-03 17:00 UTC, merged

2020-09-04 13:42 UTC, Vitaliy-ko commented on client/src/containers/ProjectLabels/AddLabelModal.tsx
> +		);
You are right I've missed it...((